### ISSUE TITLE
Lacona Looses Applications as Targets for Open Command

### ISSUE THREAD

**Issue by TechZen** [laconalabs/LaconaApp#154]
Suddenly, Lacona no longer offers to open applications but only preference panes, URLs, volumes, etc. 
![lacona looses apps - screen shot 2017-01-19 at 3 03 30 pm](https://cloud.githubusercontent.com/assets/2874035/22128833/216e7418-de68-11e6-8a86-47b2e722d5a1.jpg)

Here's a longer list:
![lacona looses apps -screen shot 2017-01-19 at 3 03 48 pm](https://cloud.githubusercontent.com/assets/2874035/22128871/545423d2-de68-11e6-8ef8-9275448bb4c0.jpg)

Another app name. Not it finds items named "pages" or having a "pages" attribute, but not the installed app. 

![lacona looses apps -screen shot 2017-01-19 at 3 04 32 pm](https://cloud.githubusercontent.com/assets/2874035/22128889/7c68cf12-de68-11e6-87d4-a2ff7486b6b2.jpg)

App Log:

[app.log.zip](https://github.com/laconalabs/LaconaApp/files/718005/app.log.zip)

No attempts to resolve yet owing to time. Just reporting. Might be a problem with extensions. Might be the result of a "(null)" path problem I've seen with other apps, largely in Setapps but also with iBooks.

**Comment by brandonhorst** [comment]
Just to confirm, you do have "Enable Open Applications" checked in the settings, correct?

![image](https://cloud.githubusercontent.com/assets/1938545/22170118/3d956256-df48-11e6-8aee-68b0e3fbccb7.png)

If you do, it appears that you have an Application on your system that for some reason does not have a Path. I'm going to add a check for this in the next release, and in the meantime I'll try to investigate what is causing this. You may be able to fix the problem immediately by refreshing your Spotlight Index with this command:

```sh
sudo mdutil -i on /
```

**Comment by LemmaEOF** [comment]
I'm having this issue as well, but with **all** applications. I definitely have open applications on, but it won't show any application, even built-ins. It doesn't even show "application" as an option for open.
![google chrome github com screen shot jan 28 2017 1 41 34 am](https://cloud.githubusercontent.com/assets/6722691/22395728/f8a2d878-e4fa-11e6-89c2-a754e0b2ccc9.png)
![discord screen shot jan 28 2017 1 39 11 am](https://cloud.githubusercontent.com/assets/6722691/22395726/f8a22e14-e4fa-11e6-951d-47ce667ea991.png)
![discord screen shot jan 28 2017 1 38 59 am](https://cloud.githubusercontent.com/assets/6722691/22395727/f8a30c58-e4fa-11e6-925e-16777968d2d5.png)

**Comment by brandonhorst** [comment]
There appears to be a bug with Spotlight that is causing problems with Lacona.

This can be almost definitely fixed by going to Terminal and running this command:

```
sudo mdutil -i on /
```

You will need to enter your administrator password. This will force Spotlight to re-index and make the bug go away. The next release of Lacona will have logic that checks for this error and prevents it.

**Comment by fbouvard** [comment]
Hi, the issue is still present. Running the above command and restarting Lacona solves it.

**Comment by brandonhorst** [comment]
This has been fixed in 1.1.4. Thank you!
